'use client';
import { useState } from 'react';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  CardFooter,
} from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Calendar, Lightbulb, Sparkles, Target, Crown, Check } from 'lucide-react';
import {
  type AiStudyPlannerOutput,
} from '@/ai/flows/ai-study-planner';
import { Skeleton } from './ui/skeleton';
import { useDoc, useMemoFirebase } from '@/firebase';
import { doc, getFirestore } from 'firebase/firestore';
import { useUserStore } from '@/hooks/use-user-store';
import Link from 'next/link';
import { Badge } from './ui/badge';
import { aiStudyPlanner } from '@/ai/flows/ai-study-planner';

export function AIStudyPlanner() {
  const [plan, setPlan] = useState<AiStudyPlannerOutput | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const firestore = getFirestore();
  const { profileId } = useUserStore();

  const userProfileRef = useMemoFirebase(() => {
    if (!profileId) return null;
    return doc(firestore, 'userProfiles', profileId);
  }, [firestore, profileId]);

  const { data: userProfile, isLoading: isProfileLoading } =
    useDoc(userProfileRef);

  const isPremiumUser = userProfile?.subscriptionTier && userProfile.subscriptionTier !== 'free';

  const handleGeneratePlan = async () => {
    if (!userProfile) return;

    setIsLoading(true);
    setPlan(null);

    const plannerInput = {
      weakestSubjects: userProfile.weakestSubjects || ['History', 'Geography'], // Mock data if not present
      upcomingExams: userProfile.upcomingExams || [{subject: 'Final Exams', date: 'in 3 weeks'}],
    };

    try {
      const result = await aiStudyPlanner(plannerInput);
      setPlan(result);
    } catch (error) {
      console.error('Failed to get AI study plan:', error);
      // Handle error state if needed
    } finally {
      setIsLoading(false);
    }
  };
  
  const renderLoading = () => (
    <div className="space-y-4 pt-2">
       <Skeleton className="h-6 w-1/4" />
       <Skeleton className="h-4 w-full" />
       <Skeleton className="h-4 w-11/12" />
       <Skeleton className="h-6 w-1/3 mt-4" />
       <Skeleton className="h-4 w-full" />
       <Skeleton className="h-4 w-5/6" />
    </div>
  );

  if (isProfileLoading) {
    return (
        <Card className="flex flex-col h-full">
            <CardHeader>
                <Skeleton className="h-8 w-1/2" />
                <Skeleton className="h-4 w-3/4" />
            </CardHeader>
            <CardContent className="flex-1 flex items-center justify-center">
                <div className="h-10 w-10 animate-spin rounded-full border-4 border-solid border-primary border-t-transparent"></div>
            </CardContent>
            <CardFooter>
                <Skeleton className="h-12 w-full" />
            </CardFooter>
        </Card>
    )
  }

  if (!isPremiumUser) {
    return (
        <Card className="flex flex-col items-center justify-center text-center h-full">
            <CardHeader>
                <div className="p-3 bg-yellow-400/20 rounded-full mx-auto">
                    <Crown className="h-10 w-10 text-yellow-500" />
                </div>
                <CardTitle className="mt-4 text-2xl">Unlock Your Personalized Study Plan</CardTitle>
                <CardDescription>Upgrade to VIP to get a custom study schedule generated by AI.</CardDescription>
            </CardHeader>
            <CardContent>
                 <ul className="space-y-2 text-left text-muted-foreground text-sm">
                    <li className="flex items-center gap-2"><Check className="h-4 w-4 text-primary" /> Automatically focus on your weakest subjects.</li>
                    <li className="flex items-center gap-2"><Check className="h-4 w-4 text-primary" /> Get a clear, day-by-day study schedule.</li>
                    <li className="flex items-center gap-2"><Check className="h-4 w-4 text-primary" /> Prepare effectively for upcoming exams.</li>
                </ul>
            </CardContent>
            <CardFooter>
                <Button asChild size="lg" className="w-full">
                    <Link href="/subscribe">Upgrade to VIP</Link>
                </Button>
            </CardFooter>
        </Card>
    )
  }


  return (
    <Card className="flex flex-col h-full">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Calendar />
          AI Study Planner
        </CardTitle>
        <CardDescription>
          Your personalized, AI-generated weekly schedule to help you ace your exams.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6 flex-1">
        {isLoading ? (
          renderLoading()
        ) : plan ? (
            <div className="space-y-4">
                {plan.weeklySchedule.map(day => (
                    <div key={day.day}>
                        <h3 className="font-bold text-lg mb-2">{day.day}</h3>
                        <div className="border-l-2 border-primary pl-4 space-y-2">
                           <p className="text-sm text-muted-foreground">{day.plan}</p>
                           {day.tip && <p className="text-xs italic text-primary/80 flex gap-2"><Lightbulb size={14}/> {day.tip}</p>}
                        </div>
                    </div>
                ))}
            </div>
        ) : (
          <div className="text-center text-muted-foreground py-8 flex flex-col items-center justify-center h-full">
            <Calendar className="h-12 w-12 text-muted-foreground/50 mb-4" />
            <p>
              Ready to get organized? Let our AI create a personalized study plan for you based on your weakest subjects and upcoming exams.
            </p>
          </div>
        )}
      </CardContent>
      <CardFooter>
        <Button
          onClick={handleGeneratePlan}
          disabled={isLoading || isProfileLoading}
          className="w-full"
        >
          {isLoading ? 'Generating Your Plan...' : 'Generate My Study Plan'}
        </Button>
      </CardFooter>
    </Card>
  );
}
